version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: true

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/deploy.sh
      timeout: 300
      owner: ec2-user
      runas: ec2-user
