name: Build and Upload to S3

on:
  push:
    branches:
      - main

env:
  S3_BUCKET_NAME: "terraform-3tier-bucket0501"
  AWS_REGION: "ap-southeast-2"

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Node.js dependencies
      run: npm install

    - name: Build static assets
      run: npm run build

    - name: Run tests
      run: vendor/bin/phpunit

    - name: Zip files
      run: zip -r my-app.zip .

    - name: Verify ZIP file creation
      run: ls -lh my-app.zip

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
        role-session-name: github-actions-session
        aws-region: ${{ env.AWS_REGION }}

    - name: Upload to S3
      run: |
        aws s3 cp my-app.zip s3://$S3_BUCKET_NAME/my-app.zip --region $AWS_REGION
        echo "File uploaded to S3://$S3_BUCKET_NAME/my-app.zip"
