name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 최신 버전 사용

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2  # 최신 버전 사용
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Zip project files
      run: |
        zip -r $GITHUB_SHA.zip ./*
      shell: bash

    - name: Upload to S3
      run: |
        aws s3 cp --region ap-southeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip

    - name: Deploy to CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name codedeploytest \
          --deployment-group-name deploygrouptest \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$GITHUB_SHA.zip
