name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Zip project files
      run: |
        zip -r your-app.zip ./*

    - name: Upload to S3
      run: |
        aws s3 cp your-app.zip s3://terraform-3tier-bucket0501/your-app.zip

    - name: Deploy to CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name codedeploy \
          --deployment-group-name deploygroup \
          --s3-location bucket=terraform-3tier-bucket0501,bundleType=zip,key=your-app.zip
